export  const FETCH_HEALTHRISK_SUCCESS = "FETCH_HEALTHRISK_SUCCESS"
export  const FETCH_HEALTHRISK_FAILURE = "FETCH_HEALTHRISK_FAILURE"
export  const FETCH_HEALTHRISK_REQUEST = "FETCH_HEALTHRISK_REQUEST"
export const FETCH_HEALTHRISK_BY_ID_SUCCESS = "FETCH_HEALTHRISK_BY_ID_SUCCESS"
export const FETCH_HEALTHRISK_BY_ID_FAILURE = "FETCH_HEALTHRISK_BY_ID_FAILURE"
export const FETCH_HEALTHRISK_BY_ID_REQUEST = "FETCH_HEALTHRISK_BY_ID_REQUEST"


